org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=false

# TOKEN SECRETO DE MAPBOX (sk.xxx) - REEMPLAZAR ABAJO
MAPBOX_DOWNLOADS_TOKEN=tu sk de mapbox
