"""crear_tablas_de_especialidades

Revision ID: 01ac6565a4b7
Revises: d676fb7e6a18
Create Date: 2026-06-04 00:53:01.195761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ac6565a4b7'
down_revision: Union[str, Sequence[str], None] = 'd676fb7e6a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_especialidades_id'), 'especialidades', ['id'], unique=False)
    op.create_table('taller_especialidad',
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taller_id'], ['perfil_talleres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('taller_id', 'especialidad_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taller_especialidad')
    op.drop_index(op.f('ix_especialidades_id'), table_name='especialidades')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
