"""crear_tabla_backups_cloud

Revision ID: 0721826f375a
Revises: 1baed30cbadf
Create Date: 2026-06-06 00:14:47.755796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0721826f375a'
down_revision: Union[str, Sequence[str], None] = '1baed30cbadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups_cloud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('key_r2', sa.String(length=255), nullable=True),
    sa.Column('tamano', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_cloud_id'), 'backups_cloud', ['id'], unique=False)
    op.create_index(op.f('ix_backups_cloud_nombre'), 'backups_cloud', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backups_cloud_nombre'), table_name='backups_cloud')
    op.drop_index(op.f('ix_backups_cloud_id'), table_name='backups_cloud')
    op.drop_table('backups_cloud')
    # ### end Alembic commands ###
