"""agregar telefono y campos de taller

Revision ID: 15689355933f
Revises: 690615d9271f
Create Date: 2026-04-18 20:26:38.876155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15689355933f'
down_revision: Union[str, Sequence[str], None] = '690615d9271f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil_talleres', sa.Column('telefono', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil_talleres', 'telefono')
    # ### end Alembic commands ###
