"""Crear tabla backups_cloud

Revision ID: 1baed30cbadf
Revises: c6f25cc0ca5b
Create Date: 2026-06-05 23:29:54.603608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1baed30cbadf'
down_revision: Union[str, Sequence[str], None] = 'c6f25cc0ca5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emergencias', 'especialidad_ia',
               existing_type=sa.VARCHAR(length=100),
               comment='Especialidad detectada por la IA para filtrar talleres',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emergencias', 'especialidad_ia',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Especialidad detectada por la IA para filtrar talleres',
               existing_nullable=True)
    # ### end Alembic commands ###
