"""crear tabla bitacora

Revision ID: 5ea595e82268
Revises: 9884f11be9e6
Create Date: 2026-04-25 23:20:18.362986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea595e82268'
down_revision: Union[str, Sequence[str], None] = '9884f11be9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bitacora',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ip', sa.String(length=50), nullable=True),
        sa.Column('agente', sa.String(length=255), nullable=True),
        sa.Column('hora', sa.Time(), nullable=True),
        sa.Column('fecha', sa.Date(), nullable=True),
        sa.Column('accion', sa.String(length=100), nullable=False),
        sa.Column('detalle', sa.String(length=500), nullable=True),
        sa.Column('id_usuario', sa.Integer(), nullable=True),
        sa.Column('id_taller', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id_taller'], ['perfil_talleres.id'], ),
        sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_id'), 'bitacora', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bitacora_id'), table_name='bitacora')
    op.drop_table('bitacora')
    # ### end Alembic commands ###
