"""rename_comercial_to_taller

Revision ID: 8f1202f1054c
Revises: 208a8cb587d1
Create Date: 2026-04-04 23:56:32.396888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1202f1054c'
down_revision: Union[str, Sequence[str], None] = '208a8cb587d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil_talleres', sa.Column('nombre_taller', sa.String(length=150), nullable=False))
    op.drop_column('perfil_talleres', 'nombre_comercial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil_talleres', sa.Column('nombre_comercial', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('perfil_talleres', 'nombre_taller')
    # ### end Alembic commands ###
