"""agregar_campo_suscripcion_activa_taller

Revision ID: 8f4fa7540181
Revises: e7b9c1a2d3f4
Create Date: 2026-06-06 11:07:37.838170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4fa7540181'
down_revision: Union[str, Sequence[str], None] = 'e7b9c1a2d3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emergencias', 'especialidad_ia',
               existing_type=sa.VARCHAR(length=100),
               comment='Especialidad detectada por la IA para filtrar talleres',
               existing_nullable=True)
    op.add_column('perfil_talleres', sa.Column('suscripcion_activa', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil_talleres', 'suscripcion_activa')
    op.alter_column('emergencias', 'especialidad_ia',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Especialidad detectada por la IA para filtrar talleres',
               existing_nullable=True)
    # ### end Alembic commands ###
