"""agregar_tabla_pagos_emergencia

Revision ID: c47833a139ff
Revises: fb5810d08cf8
Create Date: 2026-06-08 00:23:31.181191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47833a139ff'
down_revision: Union[str, Sequence[str], None] = 'fb5810d08cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos_emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_emergencia', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['nro_emergencia'], ['emergencias.nro'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_emergencia')
    )
    op.create_index(op.f('ix_pagos_emergencia_id'), 'pagos_emergencia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_emergencia_id'), table_name='pagos_emergencia')
    op.drop_table('pagos_emergencia')
    # ### end Alembic commands ###
